// GERADO de motor-agronomico/2016/culturas (102 secoes do capitulo 6, manual 2016)
window.SOLOIA_CULTURAS = [{"cultura":"arroz-irrigado","nome":"Arroz irrigado","secao":"6.1.1","grupo":"Grãos"},
{"cultura":"arroz-de-sequeiro","nome":"Arroz de sequeiro","secao":"6.1.2","grupo":"Grãos"},
{"cultura":"amendoim","nome":"Amendoim","secao":"6.1.3","grupo":"Grãos"},
{"cultura":"aveia-branca","nome":"Aveia branca","secao":"6.1.4","grupo":"Grãos"},
{"cultura":"aveia-preta","nome":"Aveia preta","secao":"6.1.5","grupo":"Grãos"},
{"cultura":"canola","nome":"Canola","secao":"6.1.6","grupo":"Grãos"},
{"cultura":"centeio","nome":"Centeio","secao":"6.1.7","grupo":"Grãos"},
{"cultura":"cevada","nome":"Cevada","secao":"6.1.8","grupo":"Grãos"},
{"cultura":"ervilha-seca-e-ervilha-forrageira","nome":"Ervilha seca e ervilha forrageira","secao":"6.1.9","grupo":"Grãos"},
{"cultura":"ervilhaca","nome":"Ervilhaca","secao":"6.1.10","grupo":"Grãos"},
{"cultura":"feijao","nome":"Feijão","secao":"6.1.11","grupo":"Grãos"},
{"cultura":"girassol","nome":"Girassol","secao":"6.1.12","grupo":"Grãos"},
{"cultura":"linho","nome":"Linho","secao":"6.1.13","grupo":"Grãos"},
{"cultura":"milho","nome":"Milho","secao":"6.1.14","grupo":"Grãos"},
{"cultura":"milho-pipoca","nome":"Milho pipoca","secao":"6.1.15","grupo":"Grãos"},
{"cultura":"nabo-forrageiro","nome":"Nabo forrageiro","secao":"6.1.16","grupo":"Grãos"},
{"cultura":"painco","nome":"Painço","secao":"6.1.17","grupo":"Grãos"},
{"cultura":"soja","nome":"Soja","secao":"6.1.18","grupo":"Grãos"},
{"cultura":"sorgo","nome":"Sorgo","secao":"6.1.19","grupo":"Grãos"},
{"cultura":"tremoco","nome":"Tremoço","secao":"6.1.20","grupo":"Grãos"},
{"cultura":"trigo","nome":"Trigo","secao":"6.1.21","grupo":"Grãos"},
{"cultura":"triticale","nome":"Triticale","secao":"6.1.22","grupo":"Grãos"},
{"cultura":"alfafa","nome":"Alfafa","secao":"6.2.1","grupo":"Forrageiras"},
{"cultura":"gramineas-de-estacao-fria","nome":"Gramíneas de estação fria","secao":"6.2.2","grupo":"Forrageiras"},
{"cultura":"gramineas-de-estacao-quente","nome":"Gramíneas de estação quente","secao":"6.2.3","grupo":"Forrageiras"},
{"cultura":"leguminosas-de-estacao-fria","nome":"Leguminosas de estação fria","secao":"6.2.4","grupo":"Forrageiras"},
{"cultura":"leguminosas-de-estacao-quente","nome":"Leguminosas de estação quente","secao":"6.2.5","grupo":"Forrageiras"},
{"cultura":"consorciacoes-de-gramineas-e-de-leguminosas-de-estacao-fria","nome":"Consorciações de gramíneas e de leguminosas de estação fria","secao":"6.2.6","grupo":"Forrageiras"},
{"cultura":"consorciacoes-de-gramineas-e-de-leguminosas-de-estacao-quente","nome":"Consorciações de gramíneas e de leguminosas de estação quente","secao":"6.2.7","grupo":"Forrageiras"},
{"cultura":"milho-e-sorgo-para-silagem","nome":"Milho e sorgo para silagem","secao":"6.2.8","grupo":"Forrageiras"},
{"cultura":"pastagens-naturais-nativas-ou-naturalizadas","nome":"Pastagens naturais","secao":"6.2.9","grupo":"Forrageiras"},
{"cultura":"pastagens-naturais-com-introducao-de-gramineas-e-leguminosas","nome":"Pastagens naturais com introdução de gramíneas e leguminosas","secao":"6.2.10","grupo":"Forrageiras"},
{"cultura":"abobora-abobrinha-e-moranga","nome":"Abóbora, abobrinha e moranga","secao":"6.3.1","grupo":"Hortaliças"},
{"cultura":"alcachofra","nome":"Alcachofra","secao":"6.3.2","grupo":"Hortaliças"},
{"cultura":"alface-almeirao-chicoria-rucula-e-salsa","nome":"Alface, almeirão, chicória, rúcula e salsa","secao":"6.3.3","grupo":"Hortaliças"},
{"cultura":"alho","nome":"Alho","secao":"6.3.4","grupo":"Hortaliças"},
{"cultura":"aspargo","nome":"Aspargo","secao":"6.3.5","grupo":"Hortaliças"},
{"cultura":"berinjela","nome":"Berinjela","secao":"6.3.6","grupo":"Hortaliças"},
{"cultura":"beterraba-e-cenoura","nome":"Beterraba e cenoura","secao":"6.3.7","grupo":"Hortaliças"},
{"cultura":"brocolis-e-couve-flor","nome":"Brócolis e couve-flor","secao":"6.3.8","grupo":"Hortaliças"},
{"cultura":"cebola","nome":"Cebola","secao":"6.3.9","grupo":"Hortaliças"},
{"cultura":"chuchu","nome":"Chuchu","secao":"6.3.10","grupo":"Hortaliças"},
{"cultura":"ervilha","nome":"Ervilha","secao":"6.3.11","grupo":"Hortaliças"},
{"cultura":"mandioquinha-salsa","nome":"Mandioquinha salsa","secao":"6.3.12","grupo":"Hortaliças"},
{"cultura":"melancia-e-melao","nome":"Melancia e melão","secao":"6.3.13","grupo":"Hortaliças"},
{"cultura":"nabo-e-rabanete","nome":"Nabo e Rabanete","secao":"6.3.14","grupo":"Hortaliças"},
{"cultura":"palmeira-real-australiana","nome":"Palmeira real australiana","secao":"6.3.15","grupo":"Hortaliças"},
{"cultura":"pepino-salada","nome":"Pepino salada","secao":"6.3.16","grupo":"Hortaliças"},
{"cultura":"pimentao","nome":"Pimentão","secao":"6.3.17","grupo":"Hortaliças"},
{"cultura":"pupunheira","nome":"Pupunheira","secao":"6.3.18","grupo":"Hortaliças"},
{"cultura":"repolho","nome":"Repolho","secao":"6.3.19","grupo":"Hortaliças"},
{"cultura":"tomateiro","nome":"Tomateiro","secao":"6.3.20","grupo":"Hortaliças"},
{"cultura":"batata","nome":"Batata","secao":"6.4.1","grupo":"Tubérculos e raízes"},
{"cultura":"batata-doce","nome":"Batata-doce","secao":"6.4.2","grupo":"Tubérculos e raízes"},
{"cultura":"mandioca","nome":"Mandioca","secao":"6.4.3","grupo":"Tubérculos e raízes"},
{"cultura":"abacateiro","nome":"Abacateiro","secao":"6.5.1","grupo":"Frutíferas"},
{"cultura":"ameixeira","nome":"Ameixeira","secao":"6.5.2","grupo":"Frutíferas"},
{"cultura":"amoreira-preta","nome":"Amoreira-preta","secao":"6.5.3","grupo":"Frutíferas"},
{"cultura":"bananeira","nome":"Bananeira","secao":"6.5.4","grupo":"Frutíferas"},
{"cultura":"caquizeiro","nome":"Caquizeiro","secao":"6.5.5","grupo":"Frutíferas"},
{"cultura":"citros","nome":"Citros","secao":"6.5.6","grupo":"Frutíferas"},
{"cultura":"figueira","nome":"Figueira","secao":"6.5.7","grupo":"Frutíferas"},
{"cultura":"macieira","nome":"Macieira","secao":"6.5.8","grupo":"Frutíferas"},
{"cultura":"maracujazeiro","nome":"Maracujazeiro","secao":"6.5.9","grupo":"Frutíferas"},
{"cultura":"mirtileiro","nome":"Mirtileiro","secao":"6.5.10","grupo":"Frutíferas"},
{"cultura":"morangueiro","nome":"Morangueiro","secao":"6.5.11","grupo":"Frutíferas"},
{"cultura":"nogueira-peca","nome":"Nogueira-pecã","secao":"6.5.12","grupo":"Frutíferas"},
{"cultura":"oliveira","nome":"Oliveira","secao":"6.5.13","grupo":"Frutíferas"},
{"cultura":"palmeira-jucara","nome":"Palmeira juçara","secao":"6.5.14","grupo":"Frutíferas"},
{"cultura":"pereira","nome":"Pereira","secao":"6.5.15","grupo":"Frutíferas"},
{"cultura":"pessegueiro-e-nectarineira","nome":"Pessegueiro e nectarineira","secao":"6.5.16","grupo":"Frutíferas"},
{"cultura":"quivizeiro","nome":"Quivizeiro","secao":"6.5.17","grupo":"Frutíferas"},
{"cultura":"videira","nome":"Videira","secao":"6.5.18","grupo":"Frutíferas"},
{"cultura":"acacia-negra","nome":"Acácia-negra","secao":"6.6.1","grupo":"Florestais"},
{"cultura":"araucaria","nome":"Araucária","secao":"6.6.2","grupo":"Florestais"},
{"cultura":"bracatinga","nome":"Bracatinga","secao":"6.6.3","grupo":"Florestais"},
{"cultura":"cedro-australiano","nome":"Cedro australiano","secao":"6.6.4","grupo":"Florestais"},
{"cultura":"erva-mate","nome":"Erva-mate","secao":"6.6.5","grupo":"Florestais"},
{"cultura":"eucalipto","nome":"Eucalipto","secao":"6.6.6","grupo":"Florestais"},
{"cultura":"pinus","nome":"Pinus","secao":"6.6.7","grupo":"Florestais"},
{"cultura":"alfavaca","nome":"Alfavaca","secao":"6.7.1","grupo":"Medicinais, aromáticas e condimentares"},
{"cultura":"calendula","nome":"Calêndula","secao":"6.7.2","grupo":"Medicinais, aromáticas e condimentares"},
{"cultura":"camomila","nome":"Camomila","secao":"6.7.3","grupo":"Medicinais, aromáticas e condimentares"},
{"cultura":"capim-limao-citronela-de-java-e-palma-rosa","nome":"Capim-limão, citronela-de-java e palma-rosa","secao":"6.7.4","grupo":"Medicinais, aromáticas e condimentares"},
{"cultura":"cardamomo","nome":"Cardamomo","secao":"6.7.5","grupo":"Medicinais, aromáticas e condimentares"},
{"cultura":"carqueja","nome":"Carqueja","secao":"6.7.6","grupo":"Medicinais, aromáticas e condimentares"},
{"cultura":"cha-verde-ou-cha-da-india","nome":"Chá-verde ou chá-da-índia","secao":"6.7.7","grupo":"Medicinais, aromáticas e condimentares"},
{"cultura":"coentro","nome":"Coentro","secao":"6.7.8","grupo":"Medicinais, aromáticas e condimentares"},
{"cultura":"curcuma","nome":"Curcuma","secao":"6.7.9","grupo":"Medicinais, aromáticas e condimentares"},
{"cultura":"erva-doce-e-funcho","nome":"Erva-doce e Funcho","secao":"6.7.10","grupo":"Medicinais, aromáticas e condimentares"},
{"cultura":"estevia","nome":"Estévia","secao":"6.7.11","grupo":"Medicinais, aromáticas e condimentares"},
{"cultura":"hortelas","nome":"Hortelãs","secao":"6.7.12","grupo":"Medicinais, aromáticas e condimentares"},
{"cultura":"gengibre","nome":"Gengibre","secao":"6.7.13","grupo":"Medicinais, aromáticas e condimentares"},
{"cultura":"guaco","nome":"Guaco","secao":"6.7.14","grupo":"Medicinais, aromáticas e condimentares"},
{"cultura":"piretro","nome":"Piretro","secao":"6.7.15","grupo":"Medicinais, aromáticas e condimentares"},
{"cultura":"urucum","nome":"Urucum","secao":"6.7.16","grupo":"Medicinais, aromáticas e condimentares"},
{"cultura":"vetiver","nome":"Vetiver","secao":"6.7.17","grupo":"Medicinais, aromáticas e condimentares"},
{"cultura":"roseira-de-corte","nome":"Roseira de corte","secao":"6.8.1","grupo":"Ornamentais"},
{"cultura":"crisantemo-de-corte","nome":"Crisântemo de corte","secao":"6.8.2","grupo":"Ornamentais"},
{"cultura":"crisantemo-de-vaso","nome":"Crisântemo de vaso","secao":"6.8.3","grupo":"Ornamentais"},
{"cultura":"cana-de-acucar","nome":"Cana-de-açúcar","secao":"6.9.1","grupo":"Outras culturas comerciais"},
{"cultura":"tabaco","nome":"Tabaco","secao":"6.9.2","grupo":"Outras culturas comerciais"}];
